spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minji_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

# application.yml
cors:
  allowed-origin: "http://localhost:5173"  # 허용할 출처
  allowed-methods: "GET,POST,PUT,DELETE"   # 허용할 메서드들 (쉼표로 구분)
