spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/minji_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false  # Spring Batch 자동 실행 비활성화

logging:
  level:
    org.springframework.batch: DEBUG

# 스케줄러 설정
task:
  scheduling:
    cron:
      reset-weekly: 0 0 0 * * MON  # 매주 월요일 00:00에 실행

cors:
  allowed-origin: "*"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE